### ISSUE TITLE
ClimateMachine.jl working with Julia 1.5.x release

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimateMachine.jl#1507]
# Description

There are currently GPU compilation errors with ClimateMachine on the new Julia 1.5 release (example build):
- https://buildkite.com/clima/climatemachine-ci/builds/185

@mwarusz has identified one KernalAbstraction issue with `eps` specialization:
https://github.com/JuliaGPU/KernelAbstractions.jl/issues/127

Suggested workaround of rewriting `eps(x)` to `x * eps(typeof(x))` breaks some of the numerical comparison tests:
- https://github.com/Clima/ClimateMachine.jl/commit/fe812a8a222fac6b5da0a20337f578089e781c70
- https://buildkite.com/clima/climatemachine-ci/builds/195

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by jakebolewski** [comment]
cc @simonbyrne

**Comment by jakebolewski** [comment]
https://github.com/JuliaGPU/KernelAbstractions.jl/pull/130 Is a possible fix / workaround for the compilation issue.

**Comment by jakebolewski** [comment]
With the above workaround, down to only 2 failures now:

https://buildkite.com/clima/climatemachine-ci/builds/290
